### ISSUE TITLE
ToLower on variables

### ISSUE THREAD

**Issue by dylan-smith** [jessehouwing/vsts-variable-tasks#1]
I want a build variable, and I want to get a lowercase version of it's value to pass to some task.

Would be nice to be able to define another variable whose value is $(foo).ToLower() or whatever syntax makes sense.

**Comment by jessehouwing** [comment]
Would a bunch op extra options on the setvariable task work for you? something like:

```
> Advanced > ----------------------------------------------------------------
 * Change Case                                       [Lowercase \/]
 * Regex Pattern [Pattern]                        [                                           ]
 * Regex Replacement                             [                                           ]
 * Trim                                                      [ Left + Right]
 * Trim Characters                                   [                                           ]
```

I may be able to think of a few others... But the general gist would be easy.

**Comment by dylan-smith** [comment]
That would work, and be better than the options available today.  But if I need to do that a bunch, does that mean I need to add a new task for each one? that seems like it would clutter up my build definition more than I might like.

**Comment by jessehouwing** [comment]
It would. I could make a separate task something like Transform
Variable(s)  which would take a list of variables, similar to the expand...
Or do both...

**Comment by jessehouwing** [comment]
Given that the ability to query all variables is not supported by Node and the Powershell3 host I'm closing this issue with the implementation of the transform task.

**Comment by corpix-net** [comment]
+1

**Comment by jessehouwing** [comment]
The transform task exists. The nice syntaxes is something you'll have to
ask in the vsts-agent repo, that's not something a task can easily provide.
