### ISSUE TITLE
Search And Replace with Nothing inserts "null"

### ISSUE THREAD

**Issue by SDxKeeper** [jessehouwing/vsts-variable-tasks#10]
I have a task to strip some symbols from variable IF they are there.
I've tried to drop "C" from C222332 using "Transform Variable" task with "Search and Replace" checked in basic mode.
In the search box I've specified "C" (without quotes)
In the replacement I've put nothing.

Result was funny: "null222332"
It's not critical but not expected behavior.

Workaround to do it is to specify " " (space) in replacement section and also enable "Trim" transformation.

**Comment by jessehouwing** [comment]
That doesn't look good :). Fixing as I type.

**Comment by jessehouwing** [comment]
Should be fixed as soon as the new version done building and has been pushed to the Visual Studio Marketplace
