### ISSUE TITLE
Expand Variables not returning values

### ISSUE THREAD

**Issue by rrober07** [jessehouwing/vsts-variable-tasks#12]
I must be doing something wrong because I left the default '*' and I am not getting anything returned...just that it executed the powershell script 

"2016-08-06T11:47:37.0752540Z Executing the powershell script: E:\VsoAgt\A89\tasks\VariableExpandTask\1.0.970\vsts-variable-expand.ps1"

I have 4 custom variables in my Release.  I setup only 1 task on the environment to test retrieving these variables...I have no other tasks
Let me know what I need to do to use this correctly.. 
Thanks
Richard

**Comment by jessehouwing** [comment]
What version of VSTS/TFS and agent? The agent that ships with VSTS nowadays expands variables by default and no longer needs this task.

The task only outputs something when a task needs expanding, so there may simply be nothing to do.

**Comment by jessehouwing** [comment]
Try setting `system.debug = true` in the global variables list to get verbose output, that should tell you more about what's going on.

**Comment by rrober07** [comment]
TFS 2015 update 2 (on premise) Version 14.95.25229.0 ... not sure of the
agent version what ever was shipped with TFS 2015

**Comment by jessehouwing** [comment]
Please update the agent to the latest version that ships with your TFS version. Preferably upgrade your TFS server to TFS 2015 update 2.1 or even TFS 2015 update 3.
