### ISSUE TITLE
Substring - Right not working

### ISSUE THREAD

**Issue by djerghiuta** [jessehouwing/vsts-variable-tasks#14]
I tried to use the transformation task to extract the last 16 characters of $(Build.BuildNumber). That part is the unique number assigned to the build. I set the parameters "substring", "right", and "16". The output variable was assigned the full build number, without any transformation.
For now I have a workaround: I use "Search and replace" to replace the beginning of the string with an empty string. It would be less confusing if I could use the substring/right function.

**Comment by jessehouwing** [comment]
A new version should be out on the marketplace now.
