### ISSUE TITLE
Can you Set deployStep tasks variables?

### ISSUE THREAD

**Issue by rrober07** [jessehouwing/vsts-variable-tasks#15]
I am wanting to dynamically control release tasks if they are to execute or not execute and if they execute have the ability to set inputs values.... so I would need the ability to set the enabled property on tasks and any inputs properties for releases tasks.  All this at run-time of the Release...is this possible with your task.  The initial idea would be to read in a control file that would define and have the control settings for the release. and make those settings at the beginning and then just flow through the Release tasks.  If not any Ideas?  

Thanks
Richard

**Comment by jessehouwing** [comment]
Don't think my tasks will help you here. And I haven't investigated enough
to say whether there is another way to do it.

**Comment by jessehouwing** [comment]
This is not possible at present. It's outside of my control unfortunately.
