### ISSUE TITLE
TFS 2015 On Premise

### ISSUE THREAD

**Issue by RyanThomas73** [jessehouwing/vsts-variable-tasks#16]
Should these tasks show up for an on premise TFS 2015 (Update 3) server if I've installed the extension? We have the extension installed but I don't see any of the tasks available as build steps.

I saw in the wiki that you state it's necessary to manually install the tasks via tfx for RTM / Update 1. I was curious if perhaps this is necessary for Update 3 as well?

https://github.com/jessehouwing/vsts-variable-tasks/wiki

**Comment by jessehouwing** [comment]
They should work ad when installed as extension in update 2 or 3 they should show up. Make sure that after installing the extension in the TFS Gallery (step 1), you also install the extension in the Project Collection. Only then will they become visible.

You may also have to upgrade your build agent to the latest version, as the tasks depend on the latest node sdk.

**Comment by RyanThomas73** [comment]
Thanks much for the response. I'll try checking the build agent version and see if that is the problem.
