### ISSUE TITLE
Transformed variable not visible in Finalize Build steps

### ISSUE THREAD

**Issue by PeterStaev** [jessehouwing/vsts-variable-tasks#20]
I'm using the plugin in an on-premises TFS 2017 server. For the normal build steps the Transform Variable works excellent, but when it comes to the Finalize Build (where it labels the sources) the variable seems is not set. For example I'm transforming by `BuildNumber` to create a `Label` variable. If I set the build to label the sources with `$(Label)` it just puts the string and does not expand the variable value.

**Comment by PeterStaev** [comment]
I've managed to overcome this limitation by using Build.BuildNumber for the transform and the label.

**Comment by jessehouwing** [comment]
I suspect this is a limitation in the agent itself. And you may want to log an issue to https://github.com/Microsoft/vsts-agent/issues

**Comment by PeterStaev** [comment]
Thanks! I've added https://github.com/Microsoft/vsts-task-lib/issues/193
