### ISSUE TITLE
Transforming BuildNumber does not update actually the build number of the build

### ISSUE THREAD

**Issue by PeterStaev** [jessehouwing/vsts-variable-tasks#21]
I have set up as the Output Variable `Build.BuildNumber` but the ctual build number is never updated. The problem is that [this check](https://github.com/jessehouwing/vsts-variable-tasks/blob/master/vsts-variable-transform/vsts-variable-transform.ts#L37) should be like `variable.search(/^Build[._]BuildNumber$/i) >= 0`. Probably the other tasks also have this problem.

**Comment by jessehouwing** [comment]
I can fix that.

**Comment by jessehouwing** [comment]
New build released
