### ISSUE TITLE
Add changeset number to build number

### ISSUE THREAD

**Issue by doodlleus** [jessehouwing/vsts-variable-tasks#22]
Hi,
As it seems I cannot use $(Build.SourceVersion) in the build number format in VSTS as it only has a scope of "Agent" and not "All", I am trying to use your extension to get what i desired.

My intended format:
$(Date:yyyyMMdd).$(Build.SourceVersion).$(Rev:.r)

Going to my build definition and the "variables" tab I am trying to add a new variable call "Build.BuildNumber" with the value of my format above.
I get an error on save saying that "Build.BuildNumber" is a reserved variable.

If i then change the variable name to "My.BuildNumber" and put the value to the format and then set my "Build Number Format" to $(My.BuildNumber) I get the following error:

400: The build number format string $(My.BuildNumber) generated a build number $(Date:yyyyMMdd).$(Build.SourceVersion).$(Rev:.r) which contains invalid character(s)

which tells me that the variable is not being expanded.

What am i doing wrong?

**Comment by jessehouwing** [comment]
I'll need to see a few screenshots of what you're trying to do.

You should not need to declare a new variable, just use the "Set Variable" task to set the value.

The problem is that $(Date) and $(Rev) are not available outside of the scope.

**Comment by doodlleus** [comment]
![image](https://cloud.githubusercontent.com/assets/7438954/22299233/4a623f28-e31b-11e6-9221-0ff24d0ce009.png)
this does not work
so i tried the following:
![image](https://cloud.githubusercontent.com/assets/7438954/22299276/69e9f5de-e31b-11e6-8000-09a740ed3dbc.png)
![image](https://cloud.githubusercontent.com/assets/7438954/22299297/74041e96-e31b-11e6-987e-8de78719b6bc.png)

which does not give me the build number i want:
![image](https://cloud.githubusercontent.com/assets/7438954/22299358/a6c5dd7e-e31b-11e6-9d60-51c45c5925f2.png)

If i try to set the variable to the build number i get the following:
![image](https://cloud.githubusercontent.com/assets/7438954/22299394/cb84a6e0-e31b-11e6-8d81-5909fca6a881.png)

Do i need to add a build step? The documentation says that it is deprecated and things should expand automatically.

**Comment by doodlleus** [comment]
as an additional thing i tried to use the "set variable" task to update the build number but get the following error:
![image](https://cloud.githubusercontent.com/assets/7438954/22300779/79dd28bc-e320-11e6-98f9-3539420935db.png)
