### ISSUE TITLE
Insufficient Documentation for Transform Value Task

### ISSUE THREAD

**Issue by sebastianlux** [jessehouwing/vsts-variable-tasks#23]
Hi,

I try to use the _Transform Value_ task to create a new variable based on _$(Build.BuildNumer)_. 

I want to achieve the following:

If _$(Build.BuildNumber)_ = __20170129.1__
Then _$(My.Variable)_ = __1701.291__

Unfortunately I cant find any documenation how to use thie _Replacement_ field. Here is my task configuration so far:
![image](https://cloud.githubusercontent.com/assets/6784951/22403890/53f8a9f2-e625-11e6-8175-831116ec0556.png)

**Comment by jessehouwing** [comment]
Check the EcmaScript links in the little (?) icons. The tasks use standard EcmaScript Regex syntax or both the search and the replace parts.

In your case you're probably looking for something like:

```
20(\d{4})(\d{2})\.(\d+)
```

and replace with:

```
$1.$2$3
```

**Comment by sebastianlux** [comment]
Thank you, it works fine now if i use `.*(\d{4})(\d{2})\.(\d+).*`
I already tried using `$1.$2$4` in the _Replacement_ field with my search pattern. Its very strange for someone like me who has no clue about regular expressions, that square brackets do not work here.
