### ISSUE TITLE
vsts-variable-transform - values lost

### ISSUE THREAD

**Issue by euhm** [jessehouwing/vsts-variable-tasks#26]
Hello,

today we changed something in our release and suddenly some values where changed in our vsts-variable-transform step, without changing anything in these steps.

It seems that the task doesn't bind correctly, and on the next save, values are overwritten with defaults (eg false for checkbox / boolean).

**Comment by jessehouwing** [comment]
Since the Ui is fully bound through the task.json definition, I'd consider
that a bug in VSTS. There is nothing I can do about that.

**Comment by euhm** [comment]
Hey, thanks for the update.

I think it only happens in the new release definition editor. I try to mail them.

**Comment by jessehouwing** [comment]
I asked a few folks to look into this issue, if you could provide as much detail of what you did when this happened. And whether you are able to reproduce it.

**Comment by nikhilexe** [comment]
@euhm @jessehouwing can you please confirm if this issue is similar to this https://github.com/Microsoft/vsts-tasks/issues/4851. If yes, fix is already rolled out for this. Please let me know if you are facing some other issue.

**Comment by euhm** [comment]
@nikhilexe it seems to be the same and I just verified the fix.

thanks!
