### ISSUE TITLE
Setting `Build.BuildNumber` fails on Windows agent

### ISSUE THREAD

**Issue by beforan** [jessehouwing/vsts-variable-tasks#28]
## Windows agent output (failure)
```
******************************************************************************
Starting: Set variable: Build.BuildNumber to: '20171117.1 $(PKG_version)'
******************************************************************************
==============================================================================
Task         : Set Variable 
Description  : Sets a variable.
Version      : 1.0.1320
Author       : Jesse Houwing
Help         : Version: 1.0.1320. [More Information](https://github.com/jessehouwing/vsts-variable-tasks/wiki/)
==============================================================================
Preparing task execution handler.
Executing the powershell script: C:\vsts-agent\_work\_tasks\VariableSetTask_3ca44a28-62de-4c60-8d77-a99065b95a8a\1.0.1320\vsts-variable-set.ps1
Setting 'Build.BuildNumber' to '20171117.1 0.1.0'.
Unable to process command '##vso[build.updatebuildnumber;]20171117.1 0.1.0' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##vso[build.updatebuildnumber;] is not a recognized command for Build command extension. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
******************************************************************************
Finishing: Set variable: Build.BuildNumber to: '20171117.1 $(PKG_version)'
******************************************************************************
```

## Linux agent output (successful)
```
2017-11-17T08:42:06.3241590Z ##[section]Starting: Set variable: Build.BuildNumber to: '20171117.2 $(PKG_version)'
2017-11-17T08:42:06.3294930Z ==============================================================================
2017-11-17T08:42:06.3306670Z Task         : Set Variable 
2017-11-17T08:42:06.3318230Z Description  : Sets a variable.
2017-11-17T08:42:06.3330100Z Version      : 1.0.1320
2017-11-17T08:42:06.3341690Z Author       : Jesse Houwing
2017-11-17T08:42:06.3353560Z Help         : Version: 1.0.1320. [More Information](https://github.com/jessehouwing/vsts-variable-tasks/wiki/)
2017-11-17T08:42:06.3365420Z ==============================================================================
2017-11-17T08:42:06.7885770Z Set buildnumber to: 20171117.2 0.1.0
2017-11-17T08:42:06.7976550Z ##[section]Async Command Start: Update Build Number
2017-11-17T08:42:07.0497280Z Update build number to 20171117.2 0.1.0 for build 1781
2017-11-17T08:42:07.0509260Z ##[section]Async Command End: Update Build Number
2017-11-17T08:42:07.0539350Z ##[section]Finishing: Set variable: Build.BuildNumber to: '20171117.2 $(PKG_version)'
```

My own powershell script as follows is successful:

``` powershell
Write-Host "##vso[build.updatebuildnumber]$(Build.BuildNumber) $(PKG_version)"
```

The only difference I can see is I don't have a `;` after `updatebuildnumber`.

I'd rather use your task than the powershell one though, as the Powershell task gives the Phase a demand of `DotNetFramework` and limits which of my available agents the build can run on (And using the Shell task does the same thing, but with the `sh` demand instead).

**Comment by jessehouwing** [comment]
Looks like a quick thing to fix

But also a regression in the VSTS agent.

Would you be able to make a pull request to get rid of the ;?

**Comment by beforan** [comment]
yeah no problem

**Comment by jessehouwing** [comment]
Hmm looks like it's not going to be that easy. I'm using the task library to invoke a log command. So it may include updating to the latest task library. I'm going to report this to the agent repo to see what's the underlying issue.

**Comment by jessehouwing** [comment]
Possibly fixed by #29. Can you check if this solves your issues?

**Comment by beforan** [comment]
I'll check it out. how does vsts get an updated task version?

**Comment by jessehouwing** [comment]
Automatically.

**Comment by beforan** [comment]
spot on. this is working now. 🎉

**Comment by TingluoHuang** [comment]
@beforan can you share the content from your agent box?
`C:\vsts-agent\_work\_tasks\VariableSetTask_3ca44a28-62de-4c60-8d77-a99065b95a8a\1.0.1320\vsts-variable-set.ps1`

**Comment by jessehouwing** [comment]
That was an older version of the plugin which still had a semicolon after the update buildnumber command:

https://github.com/jessehouwing/vsts-variable-tasks/commit/0cc7690f269f71064fdafe6b7dd7cf1228a96497#diff-8091181cc49afd83805067bd54955df1R18

That used to work and seems to work on Linux, but got broken with some release of the 2.x agent.

**Comment by TingluoHuang** [comment]
your task will run `.ps1` on windows but `.js` on linux, so linux always works

**Comment by beforan** [comment]
@TingluoHuang that `.ps1` file on the agent is surely the same as the one in this repo?

Either way, it is now the newer version as per the diff, so my *successful* windows run earlier ran the following:

`C:\vsts-agent\_work\_tasks\VariableSetTask_3ca44a28-62de-4c60-8d77-a99065b95a8a\1.2.2\vsts-variable-set.ps1`

note the higher version number compared to my previous log, due to the updated task as per this fix.
