### ISSUE TITLE
 Build Counter variable.

### ISSUE THREAD

**Issue by Farzad-Jalali** [jessehouwing/vsts-variable-tasks#30]
it's more question/suggestion rather than issue.
I like to have a  "Build Counter variable" for each project separately, so I thought maybe I can use your product to update a variable for each project and then use it as part of the version number (the patch). there is another tool to set the version number which I can use.

is it possible to do it with your product? (building a "build counter variable)

**Comment by jessehouwing** [comment]
The variable tasks don't persist, they are only alive during the build
itself. So my tasks would be of no good.

There is another extension that will update the base variable as defined in
the build definition itself on the marketplace if I'm not mistaking.

Is BuildId not an option for you?

**Comment by Farzad-Jalali** [comment]
thanks for the reply,
The BuildId increase cross al projects/builds/repos , that's why it doesn't work.

by any chance, can you remember the name of the other extension that you said?  (the one that can update the base variables.)

thanks

**Comment by jessehouwing** [comment]
https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-BuildUpdating-Tasks
