### ISSUE TITLE
Regex match: incorrectly warnds of multiple matches

### ISSUE THREAD

**Issue by djerghiuta** [jessehouwing/vsts-variable-tasks#31]
TFS 2015 u3 on-prem
Defined variable InputValue with value App_Name-3.0.0-b20180205092404
Using step Transform Value with parameters:
- Input Value: $(InputValue)
- Output Value: VersionNumber
- Search and Replace: checked
- Method: Regex Match
- Search: \d*[.]\d*[.]\d*(-b\S*)?

When I run the build, the VersionNumber variable gets the correct value (3.0.0-b20180205092404) but a warning gets logged: ##[warning]Found multiple matches, setting the first

This scenario should have a single match, because the ? operator is greedy. 
It seems that the JavaScript match() method also returns the group matches in the results array, and the code incorrectly treats them as additional matches. 
I found this article that confirms that only the first element in the array is the full match, the others are just group matches: http://eloquentjavascript.net/09_regexp.html

So functionality is correct, but the warning creates confusion for some users.

**Comment by jessehouwing** [comment]
Are you able to provide a PR?

**Comment by jessehouwing** [comment]
A review would be appreciated.

**Comment by djerghiuta** [comment]
Looks good. I put a comment on the commit.
Sorry, I'm new to this, I'm not familiar with the protocol for open source collaboration.
