### ISSUE TITLE
pad option apparently not working

### ISSUE THREAD

**Issue by tac01** [jessehouwing/vsts-variable-tasks#32]
I'm trying to transform a variable holding a 1 or 2 digit value into another variable as a 2 digit value with a leading 0 added as necessary (e.g. if the input var was '1', I'd want the output to be '01'). I've created a Transform value task with the single digit variable as the Input Value and the name of a variable to hold the padded 2-digit value, I have checked the 'Pad' box, and set 'Left' and Character to 0 and length to 2. But instead of being padded the resulting value is just the right-most digit from the input variable (e.g. it is just '2' if the input variable value was '12').

**Comment by jessehouwing** [comment]
What happens when you swap the values? Looks like I made a order of parameters mistake.

**Comment by tac01** [comment]
Hi Jesse, which values do you mean? I tried swapping the length and char but it just yielded an empty value (presuambly a string of length '0', so correct).

**Comment by jessehouwing** [comment]
Darn. Ok, will need to find some time to debug. It's been ages ago and I've swapped machines in the mean time, so it may require a bit longer to figure out. I wonder whether there is some weird number conversion going on...

**Comment by tac01** [comment]
Pardon my ignorance, but does this mean I can now download a new revision of the task defintion, or do I have to wait for a new release or something?

**Comment by jessehouwing** [comment]
If you're om vsts you should now automatically have the new version.

**Comment by jessehouwing** [comment]
A review would be appreciated.

**Comment by tac01** [comment]
Sorry, just testing it. Thats fixed the issue - thanks very much for the prompt response.

**Comment by racekarl** [comment]
I am having the same issue in version 1.3.6 in Azure DevOps Server 2019.

Here is an excerpt of debug output from my pipeline task:

```
##[debug]pad=true
##[debug]Applying selected Pad.
##[debug]padType=left
##[debug]padChar=.
##[debug]padLength=5
##[debug]variableName=Internal.CompactCommaSeparatedVersion
##[debug]set Internal.CompactCommaSeparatedVersion=4,1,1,20191216008
##[debug]Processed: ##vso[task.setvariable variable=Internal.CompactCommaSeparatedVersion;issecret=false;]4,1,1,20191216008
Set Internal.CompactCommaSeparatedVersion to: 4,1,1,20191216008
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]Set Internal.CompactCommaSeparatedVersion to: 4,1,1,20191216008
##[section]Finishing: Set Internal.CompactCommaSeparatedVersion value
```
It reports the pad variables correctly (pad=true, padType=left, padChar = ".", padLength=5) but you can see the final variable does not contain the pad: "4,1,1,20191216008"
