### ISSUE TITLE
No Tasks Showing up In Task List

### ISSUE THREAD

**Issue by omayhemo** [jessehouwing/vsts-variable-tasks#35]
When I try to add the setvariable task to my build, it doesn't exist.  Extension says it's installed.

**Comment by jessehouwing** [comment]
Vsts? Tfs? Which version?

Tried disabling + reenabling the extension?
Tried uninstalling + reinstalling the extension?

**Comment by omayhemo** [comment]
VSTS

**Comment by omayhemo** [comment]
I did all of that.  It never showed up in the list.  I gave up and moved on.

**Comment by jessehouwing** [comment]
Sounds like a bug on vsts. Sorry that it doesn't work, there is very little I can do to help diagnose from my end.
