### ISSUE TITLE
Utility Tasks does not show up on Agentless phase

### ISSUE THREAD

**Issue by salixzs** [jessehouwing/vsts-variable-tasks#36]
On newest Phases approach there is agentless phase which can deal with stuff without a need for agent to run on. Currently all tasks of this extension does not show up in this phase, however IMHO they should as there is no need to have agent to them.

**Comment by jessehouwing** [comment]
Server phases can only run a single task and any variable set through the tasks is list once the phase completes.

I don't see how these tasks could be useful in an agent less phase.

Can you tell me about the scenario you'd like to use?

**Comment by salixzs** [comment]
If global build variables are lost, then yes, it is pointless. I was planning to set global variable based on built-in variables, uzing transform task.

**Comment by jessehouwing** [comment]
The new output variables may work, but I need an agent to issue the
commands to change them. There is no way for a server task to issue those
commands.

So you'll need an agent phase, though it's possible to Uncheck all artifact
dependencies and source syncs to make the phase really fast.

**Comment by salixzs** [comment]
Thank you for explanations and this extension altogether. Closing this.
