### ISSUE TITLE
New task "Transform Variable(s)"

### ISSUE THREAD

**Issue by jessehouwing** [jessehouwing/vsts-variable-tasks#5]
similar to the advanced Set Variable task, so with "conditionals" and "advanced" section, but instead of setting a value from another source, it simply applies to one or more variables.

 * [x] Escape string (addslashes) 
 * [ ] Html encode string 
 * [x] Uri encode string 
 * [x] Base 64 encode string
 * [x] Search & Replace Basic
 * [x] Search & Replace Regex

**Comment by essenius** [comment]
I'd like to see an unescape transformation, so e.g. C:\Data\MyFolder becomes C:\\Data\\MyFolder.

**Comment by jessehouwing** [comment]
Looks like GitHub already use scape this... Can you edit the request and
stitck it between triple back ticks?

**Comment by essenius** [comment]
done

**Comment by jessehouwing** [comment]
Makes sense... I can imagine a few transforms 

Escape string (addslashes) 
Html encode string 
Uri encode string 
Base 64 encode string 

Those shouldn't be hard, though I'd love to put these in typescript instead of powershell.

**Comment by jessehouwing** [comment]
Not sure when I'll get to these, it's a bit busy at the moment. But definite value in these.

**Comment by jessehouwing** [comment]
@essenius started work on a new task to implement this behavior using Node (to make it work in cross platform scenarios).

You can find the code here:
https://github.com/jessehouwing/vsts-variable-tasks/tree/features/transform-typescript

if you have a test VSTS account I can share to, I'd be able to give you access to the latest version for feedback.

**Comment by jessehouwing** [comment]
Since javascript doesn't have a built-in addslashes stripslashes method I'm currently using JSON.Strinify and JSON.Parse. I'm not entirely sure this is the best idea yet. I'll have to build a few test cases.

**Comment by essenius** [comment]
Sounds good. Send me an email (think you still know that) with your user account info and I'll add you to my test VSTS account.
